### ISSUE TITLE
Idea : Whitelist some requests

### ISSUE THREAD

**Issue by K3UL** [brunobastosg/insomnia-plugin-ask-before-sending#1]
Hello, and thank you for a great plugin. This should be included in Insomnia !
I don't know if you are still maintaining it, but I would like to request a feature : the ability to exclude a request, which would then not require a confirmation.

I don't know it this is doable or should be done at the request or the environment level, but I think it would be practical for cases like me where you need to make POST requests for getting an authentication token. 

What happens is that I am doing GET requests (which I did not include in the config of the plugin) but since I have a workflow to ask for an Oauth token, and since this token is asked through a POST, I still have to confirm my request.

**Comment by brunobastosg** [comment]
Yes, I'm still mantaining it. Thanks for your suggestion. I'm gonna try to implement it.

**Comment by brunobastosg** [comment]
@K3UL just released a new version with this feature. Check out the new README.

As of now, the Insomnia Plugins website stills shows [the old version](https://insomnia.rest/plugins/insomnia-plugin-ask-before-sending). But you can install it manually following the steps from the README.
